name: Auto Update
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 13 * * *' # runs at 13:00 UTC every day.

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.runpy.outputs.NP }}

    steps:
      # actions/checkout@v4
      - name: checkout repo content
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # fregante/setup-git-user@v2 -> Pin to v2.0.2
      - name: setup git user
        uses: fregante/setup-git-user@019089938883652615467362a22026857640c663

      # actions/setup-python@v5 -> Pin to v5.1.0
      - name: setup python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script 
        id: runpy
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          output=$(python exfor_trans.py)
          echo "NP=$output" >> $GITHUB_OUTPUT

      - name: create release using REST API
        shell: bash
        run: |
          for not_processed in ${{ steps.runpy.outputs.NP }}; do
            echo "Processing: $not_processed"

            tagname="Backup-$not_processed"
            sem_release=$(bash ${GITHUB_WORKSPACE}/script/semantic_release_name.sh "$not_processed")
            
            echo "Tag: $tagname"
            echo "Release Name: $sem_release"

            curl -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            --header "Accept: application/vnd.github+json" \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data "{
              \"tag_name\": \"$tagname\",
              \"name\": \"$sem_release\",
              \"draft\": false,
              \"prerelease\": false,
              \"generate_release_notes\": false
              }" \
              --fail
          done

      - name: run entry update list file script and commit file
        run: |
          if [[ -n "${{ steps.runpy.outputs.NP }}" ]]
          then
            bash ${GITHUB_WORKSPACE}/script/get_update_date.sh > entry_updatedate.dat
            git add entry_updatedate.dat
            git commit -m "update entry_updatedate.dat"
            git push origin main
          else
            echo "no update"
          fi
